# AgenticOps Value Train Pipeline Configuration
# Defines phases, modes, agent ownership, and artifact management

metadata:
  name: "AgenticOps Value Train"
  version: "1.0.0"
  description: "AI-driven value delivery system for ML pipelines"
  project: "agenticops-value-train"

# Pipeline Phases - Sequential flow through the ML lifecycle
phases:
  # Pre-Engagement Phases
  - name: "opportunity"
    description: "Qualify and assess AI opportunity"
    mode: "intake"
    owner: "onboarder"
    artifacts:
      - "opportunity-brief.md"
    next_phase: "discovery"
    
  - name: "discovery"
    description: "Elicit context, define use case, align objectives"
    mode: "discover"
    owner: "onboarder"
    artifacts:
      - "use-case-one-pager.md"
      - "ai-readiness.md"
      - "data-profiler.ipynb"
    next_phase: "readiness"
    
  - name: "readiness"
    description: "Assess data, systems, team, and constraints"
    mode: "discover"
    owner: "onboarder"
    artifacts:
      - "readiness-questionnaire.md"
      - "risk-profile.md"
    next_phase: "scope"
    
  - name: "scope"
    description: "Define MVP scope, pricing, and delivery plan"
    mode: "scope"
    owner: "onboarder"
    artifacts:
      - "sow-template.md"
      - "pitch-deck-template.pptx"
      - "mvp-plan.md"
    next_phase: "pre-kickoff"
    
  - name: "pre-kickoff"
    description: "Confirm legal, technical, and team alignment"
    mode: "scope"
    owner: "onboarder"
    artifacts:
      - "dpa-template.docx"
      - "access-checklist.md"
      - "contact-sheet.md"
    next_phase: "data-sources"

  # Delivery Phases
  - name: "data-sources"
    description: "Identify data assets and export strategies"
    mode: "design"
    owner: "lab"
    artifacts:
      - "source-map.md"
      - "data-access-plan.md"
    next_phase: "extraction"
    
  - name: "extraction"
    description: "Pull, clean, standardize raw input into structured form"
    mode: "build"
    owner: "lab"
    artifacts:
      - "extract.py"
      - "extraction-log.md"
    next_phase: "preparation"
    
  - name: "preparation"
    description: "Handle missing values, partition sets, validate input schema"
    mode: "build"
    owner: "lab"
    artifacts:
      - "prepared.csv"
      - "schema-spec.md"
    next_phase: "exploration"
    
  - name: "exploration"
    description: "Profile features, classes, distribution, anomalies"
    mode: "build"
    owner: "lab"
    artifacts:
      - "profile.ipynb"
      - "profile-report.md"
    next_phase: "feature-engineering"
    
  - name: "feature-engineering"
    description: "Generate derived features from SIGs, quantities, etc."
    mode: "build"
    owner: "lab"
    artifacts:
      - "feature-map.md"
      - "feature-config.yaml"
    next_phase: "training"
    
  - name: "training"
    description: "Train models, log experiments, tune hyperparameters"
    mode: "build"
    owner: "lab"
    artifacts:
      - "train.ipynb"
      - "mlflow-runs.md"
    next_phase: "validation"
    
  - name: "validation"
    description: "Evaluate model performance against business-aligned metrics"
    mode: "evaluate"
    owner: "evaluator"
    artifacts:
      - "eval-results.pdf"
      - "validation-report.md"
    next_phase: "deployment"
    
  - name: "deployment"
    description: "Deploy model as batch/API, tag infra, configure rollback"
    mode: "deliver"
    owner: "ops"
    artifacts:
      - "deploy.yaml"
      - "deployment-config.md"
    next_phase: "monitoring"
    
  - name: "monitoring"
    description: "Track performance, usage, cost, drift"
    mode: "operate"
    owner: "ops"
    artifacts:
      - "dashboard-link.txt"
      - "monitoring-config.yaml"
    next_phase: "evaluation"
    
  - name: "evaluation"
    description: "Compare to baselines, SME feedback, business value"
    mode: "evaluate"
    owner: "evaluator"
    artifacts:
      - "champion-log.md"
      - "business-impact.md"
    next_phase: "improvement"
    
  - name: "improvement"
    description: "Refine features, annotations, interfaces"
    mode: "improve"
    owner: "improver"
    artifacts:
      - "improvement-roadmap.md"
      - "retraining-plan.md"
    next_phase: "retraining"
    
  - name: "retraining"
    description: "Trigger retraining, run new versions, log improvements"
    mode: "improve"
    owner: "improver"
    artifacts:
      - "retrain.ipynb"
      - "performance-comparison.md"
    next_phase: "monitoring"

# Mode Definitions - Operating contexts for agent work
modes:
  - name: "intake"
    description: "Qualify lead, capture opportunity brief, decide Go/No-Go"
    agents: ["onboarder"]
    allowed_tools: ["Read", "Write", "TodoWrite", "Bash(git:*)", "Bash(gh:*)"]
    
  - name: "discover"
    description: "Workshops, data samples, risk and readiness scoring"
    agents: ["onboarder"]
    allowed_tools: ["Read", "Write", "TodoWrite", "Bash(git:*)", "Bash(gh:*)", "WebFetch"]
    
  - name: "scope"
    description: "Produce MVP plan, SOW, pricing, pitch"
    agents: ["onboarder", "conductor"]
    allowed_tools: ["Read", "Write", "TodoWrite", "Bash(git:*)", "Bash(gh:*)"]
    
  - name: "design"
    description: "Architect data flow, feature plan, model approach"
    agents: ["studio", "lab"]
    allowed_tools: ["Read", "Write", "TodoWrite", "Bash(git:*)", "Bash(gh:*)", "Bash(python:*)"]
    
  - name: "build"
    description: "Extract data, engineer features, train models"
    agents: ["lab", "studio"]
    allowed_tools: ["Read", "Write", "TodoWrite", "Bash(git:*)", "Bash(gh:*)", "Bash(python:*)", "Bash(test:*)"]
    
  - name: "evaluate"
    description: "Formal validation against metrics and business KPIs"
    agents: ["evaluator"]
    allowed_tools: ["Read", "Write", "TodoWrite", "Bash(git:*)", "Bash(gh:*)", "Bash(python:*)", "Bash(test:*)"]
    
  - name: "deliver"
    description: "Final tests, package artifacts, create PR or release"
    agents: ["studio", "ops"]
    allowed_tools: ["Read", "Write", "TodoWrite", "Bash(git:*)", "Bash(gh:*)", "Bash(test:*)"]
    
  - name: "operate"
    description: "Watch live performance, drift, cost, error budgets"
    agents: ["ops", "evaluator"]
    allowed_tools: ["Read", "Write", "TodoWrite", "Bash(git:*)", "Bash(gh:*)", "WebFetch"]
    
  - name: "improve"
    description: "Root-cause analysis, retraining, roadmap updates"
    agents: ["improver", "lab"]
    allowed_tools: ["Read", "Write", "TodoWrite", "Bash(git:*)", "Bash(gh:*)", "Bash(python:*)", "Bash(test:*)"]

# Agent Roles - Specialized expertise areas
agents:
  - name: "conductor"
    description: "Leads the value train from planning to delivery"
    responsibilities:
      - "Coordinates handoffs between agents"
      - "Ensures business alignment"
      - "Resolves cross-agent blockers"
    
  - name: "onboarder"
    description: "Owns pre-engagement success"
    responsibilities:
      - "Aligns client expectations and deliverables"
      - "Assesses client readiness"
      - "Manages stakeholder relationships"
    
  - name: "lab"
    description: "Handles data profiling, extraction, cleaning, and modeling"
    responsibilities:
      - "Data pipeline development"
      - "Feature engineering"
      - "Model training and experimentation"
    
  - name: "studio"
    description: "Designs models, architecture, and inference systems"
    responsibilities:
      - "System architecture design"
      - "Model deployment strategies"
      - "Integration planning"
    
  - name: "ops"
    description: "Provisions cloud resources, manages IAM, cost tagging, monitoring"
    responsibilities:
      - "Infrastructure provisioning"
      - "Deployment automation"
      - "Monitoring and alerting"
    
  - name: "evaluator"
    description: "Defines and validates model quality"
    responsibilities:
      - "Performance metrics definition"
      - "Quality assurance"
      - "Business impact assessment"
    
  - name: "improver"
    description: "Optimizes features, feedback loops, retraining cadence"
    responsibilities:
      - "Performance optimization"
      - "Feedback loop design"
      - "Continuous improvement"

# Artifact Paths - Structured storage for deliverables
artifact_paths:
  preengagement:
    base_path: "/preengagement"
    framing: "/preengagement/framing"
    discovery: "/preengagement/discovery"
    legal: "/preengagement/legal"
    planning: "/preengagement/planning"
    pitch: "/preengagement/pitch"
    communication: "/preengagement/communication"
    
  delivery:
    base_path: "/delivery"
    data: "/delivery/data"
    exploration: "/delivery/exploration"
    features: "/delivery/features"
    model: "/delivery/model"
    validation: "/delivery/validation"
    deploy: "/delivery/deploy"
    monitor: "/delivery/monitor"
    evaluation: "/delivery/evaluation"
    performance: "/delivery/performance"
    improvement: "/delivery/improvement"
    retrain: "/delivery/retrain"