name: Pre-commit Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check for unchecked TODO items
      run: |
        # Get the active mode from ACTIVE_SESSION.md
        MODE=$(grep -A 10 "^mode:" docs/session-context/ACTIVE_SESSION.md | grep "mode:" | cut -d'"' -f2)
        echo "Active mode: $MODE"
        
        # Run TODO validation for active checklist
        python scripts/check_todo.py --checklist "docs/rules/checklists/${MODE}-checklist.md"
    
    - name: Validate artifact requirements
      run: |
        python scripts/check_artifacts.py --config config/pipeline.yml
    
    - name: Check session context integrity
      run: |
        python scripts/conductor_update.py --session docs/session-context/ACTIVE_SESSION.md --validate-only
    
    - name: Comment on PR if validation fails
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ **Pre-commit validation failed**\n\nPlease check:\n- [ ] All TODO items in active checklist are completed\n- [ ] Required artifacts are present\n- [ ] Session context is valid\n\nRun the validation scripts locally to debug issues.'
          })